[[Trilinos]]
arch = "aarch64"
git-tree-sha1 = "a6f256799544bcb26b290272612c7f6286da7801"
libgfortran_version = "5.0.0"
os = "macos"

    [[Trilinos.download]]
    sha256 = "8b2be91f46cfe6102975c7d747ce13b123c5d8d259cb69a953a18816848c91e6"
    url = "https://github.com/JuliaBinaryWrappers/Trilinos_jll.jl/releases/download/Trilinos-v14.4.0+0/Trilinos.v14.4.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Trilinos]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9e53c107b9b158927c412295bad87c50bc249b15"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Trilinos.download]]
    sha256 = "7e1effdea1b1b6872d7a9f8ffc8cb98d25adc715f376464de3ade79bff6ebfa1"
    url = "https://github.com/JuliaBinaryWrappers/Trilinos_jll.jl/releases/download/Trilinos-v14.4.0+0/Trilinos.v14.4.0.aarch64-linux-gnu-libgfortran5-cxx03.tar.gz"
[[Trilinos]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bead2317a84b27bea3dfcc9d4cb9ff77a145c871"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Trilinos.download]]
    sha256 = "0c76d18422ee45d2301a579b262b525f84dd6587aec73cf204be0222934dbe87"
    url = "https://github.com/JuliaBinaryWrappers/Trilinos_jll.jl/releases/download/Trilinos-v14.4.0+0/Trilinos.v14.4.0.aarch64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[Trilinos]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aac8f9a65a16050f19fa334cae385b364980fa7c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Trilinos.download]]
    sha256 = "46bf80c992c30101ae9858436f554aed0a6b58812ecc28c40702d48cbb86eb69"
    url = "https://github.com/JuliaBinaryWrappers/Trilinos_jll.jl/releases/download/Trilinos-v14.4.0+0/Trilinos.v14.4.0.aarch64-linux-musl-libgfortran5-cxx03.tar.gz"
[[Trilinos]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c18a9e2a165435baca159f1c24180916d9a6d93d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Trilinos.download]]
    sha256 = "8c9aff1b361f3c9fa1031c709d787560368de6f9b492f2715c9116e9825e873b"
    url = "https://github.com/JuliaBinaryWrappers/Trilinos_jll.jl/releases/download/Trilinos-v14.4.0+0/Trilinos.v14.4.0.aarch64-linux-musl-libgfortran5-cxx11.tar.gz"
[[Trilinos]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "721a167f01913f9695c91476a21a1b84163eb441"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Trilinos.download]]
    sha256 = "2dbee901dc2a94c1341cff4f4fbbd16984528c6f81b4e2267fc64e74e8ec7c89"
    url = "https://github.com/JuliaBinaryWrappers/Trilinos_jll.jl/releases/download/Trilinos-v14.4.0+0/Trilinos.v14.4.0.armv6l-linux-gnueabihf-libgfortran5-cxx03.tar.gz"
[[Trilinos]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "177618c2547fb95446f877ec29dae17f8c98b338"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Trilinos.download]]
    sha256 = "4d22e093c17fb20815296ef13f0eed4779df4763c09cf7f7f2ad9ae1fa7e8dea"
    url = "https://github.com/JuliaBinaryWrappers/Trilinos_jll.jl/releases/download/Trilinos-v14.4.0+0/Trilinos.v14.4.0.armv6l-linux-gnueabihf-libgfortran5-cxx11.tar.gz"
[[Trilinos]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a00d77f2d81f503a1ec21d926551274792cf5743"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Trilinos.download]]
    sha256 = "773fc094a324fb0f92addf4acc37dc2b114a6ccc42515f7911faf706f98cf2a8"
    url = "https://github.com/JuliaBinaryWrappers/Trilinos_jll.jl/releases/download/Trilinos-v14.4.0+0/Trilinos.v14.4.0.armv6l-linux-musleabihf-libgfortran5-cxx03.tar.gz"
[[Trilinos]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "afc8e017441e224ff586563a1c22361ecdddb81a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Trilinos.download]]
    sha256 = "3b6cc7c6d7857b783762d4e4f1521dd020e6286be6da7b4aac99dab60b9813fe"
    url = "https://github.com/JuliaBinaryWrappers/Trilinos_jll.jl/releases/download/Trilinos-v14.4.0+0/Trilinos.v14.4.0.armv6l-linux-musleabihf-libgfortran5-cxx11.tar.gz"
[[Trilinos]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "955976eeec1c8fc44cc49ef2b2721431afe13a5e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Trilinos.download]]
    sha256 = "d3e488a19563140f1629f875b0e2700165f9f75bcdaebcf6089d66c6bc0ab526"
    url = "https://github.com/JuliaBinaryWrappers/Trilinos_jll.jl/releases/download/Trilinos-v14.4.0+0/Trilinos.v14.4.0.armv7l-linux-gnueabihf-libgfortran5-cxx03.tar.gz"
[[Trilinos]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a01fb94d54c03a3da342cb3f48f30f3e1586203"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Trilinos.download]]
    sha256 = "09afc064c42ab302992295b9d5f087675f4346bc4c28f5fc6a33c2068f50826f"
    url = "https://github.com/JuliaBinaryWrappers/Trilinos_jll.jl/releases/download/Trilinos-v14.4.0+0/Trilinos.v14.4.0.armv7l-linux-gnueabihf-libgfortran5-cxx11.tar.gz"
[[Trilinos]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f4ca8785f5f7af82fc8563933a13fa6d4c602468"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Trilinos.download]]
    sha256 = "6ba4a283d06b5d2a512fb9f39356704cd4aea7b8faf92d389adc8fcc4f0f3090"
    url = "https://github.com/JuliaBinaryWrappers/Trilinos_jll.jl/releases/download/Trilinos-v14.4.0+0/Trilinos.v14.4.0.armv7l-linux-musleabihf-libgfortran5-cxx03.tar.gz"
[[Trilinos]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c7e7326bcce0d0ba1a2e42fa2bd0cecc5ae6ae5"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Trilinos.download]]
    sha256 = "2d78dc33b252d2265a34e6238ae95f4e9a67f2496da3e521a4fdc09083c4b233"
    url = "https://github.com/JuliaBinaryWrappers/Trilinos_jll.jl/releases/download/Trilinos-v14.4.0+0/Trilinos.v14.4.0.armv7l-linux-musleabihf-libgfortran5-cxx11.tar.gz"
[[Trilinos]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b3d3bc77be351d136921b1c8184d2c6b14ac0fda"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Trilinos.download]]
    sha256 = "dc467a0a339c75cc5c343261e88d8c0bf719f1f9fbfb16e4f0242a8d25ba0c47"
    url = "https://github.com/JuliaBinaryWrappers/Trilinos_jll.jl/releases/download/Trilinos-v14.4.0+0/Trilinos.v14.4.0.i686-linux-gnu-libgfortran5-cxx03.tar.gz"
[[Trilinos]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a0cbd4dfd7fb1fdf2b52033eb0a98fa1e559d6b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Trilinos.download]]
    sha256 = "d48764a5afe5c29cd7b120826b249987453faeedfcffd90ee5e13a6b8ae5cc1f"
    url = "https://github.com/JuliaBinaryWrappers/Trilinos_jll.jl/releases/download/Trilinos-v14.4.0+0/Trilinos.v14.4.0.i686-linux-gnu-libgfortran5-cxx11.tar.gz"
[[Trilinos]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "880f3a4fa4fa3b8c7722b4afc7d6dc69040db226"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Trilinos.download]]
    sha256 = "94a4e40f7b6340d03307005ea265ed8c622291f6067168afbc0a984974c54ccb"
    url = "https://github.com/JuliaBinaryWrappers/Trilinos_jll.jl/releases/download/Trilinos-v14.4.0+0/Trilinos.v14.4.0.i686-linux-musl-libgfortran5-cxx03.tar.gz"
[[Trilinos]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72d2c8bcb0ca7aa75f03a353c2d273590dd99e97"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Trilinos.download]]
    sha256 = "8d4953b040fcedb5cbe6be67a281e9c85a49ac1494d6274277c79e0199567805"
    url = "https://github.com/JuliaBinaryWrappers/Trilinos_jll.jl/releases/download/Trilinos-v14.4.0+0/Trilinos.v14.4.0.i686-linux-musl-libgfortran5-cxx11.tar.gz"
[[Trilinos]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b87e4ce6b42949c95686a9bdadde44f14afb7057"
libgfortran_version = "5.0.0"
os = "windows"

    [[Trilinos.download]]
    sha256 = "426e841e144669765f7667660fbe0bcd110d1c61c291d115f5eee56796eac067"
    url = "https://github.com/JuliaBinaryWrappers/Trilinos_jll.jl/releases/download/Trilinos-v14.4.0+0/Trilinos.v14.4.0.i686-w64-mingw32-libgfortran5-cxx03.tar.gz"
[[Trilinos]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9940304bf2f25857dbdd8fbb54d731735ef471a6"
libgfortran_version = "5.0.0"
os = "windows"

    [[Trilinos.download]]
    sha256 = "b28d588ab3db68bf73982beb3221432dbbc26b2780f19faa51c245648a0c4e5c"
    url = "https://github.com/JuliaBinaryWrappers/Trilinos_jll.jl/releases/download/Trilinos-v14.4.0+0/Trilinos.v14.4.0.i686-w64-mingw32-libgfortran5-cxx11.tar.gz"
[[Trilinos]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3118172c7813ca16fe6cd0d464421f5733969404"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Trilinos.download]]
    sha256 = "9ebbd260b32ca3a95b7ea34914d820d69165a6090fbe74f799f1ae787d33f8fd"
    url = "https://github.com/JuliaBinaryWrappers/Trilinos_jll.jl/releases/download/Trilinos-v14.4.0+0/Trilinos.v14.4.0.powerpc64le-linux-gnu-libgfortran5-cxx03.tar.gz"
[[Trilinos]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a907d50499a237864cf2ea6981031372c636397f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Trilinos.download]]
    sha256 = "e8e78dbcb13e6537c186a469dfa4f63ca67d9148df7a1c21b14d34765742300d"
    url = "https://github.com/JuliaBinaryWrappers/Trilinos_jll.jl/releases/download/Trilinos-v14.4.0+0/Trilinos.v14.4.0.powerpc64le-linux-gnu-libgfortran5-cxx11.tar.gz"
[[Trilinos]]
arch = "x86_64"
git-tree-sha1 = "2e56b6e99804304c46322b059c305ef300c96d14"
libgfortran_version = "5.0.0"
os = "macos"

    [[Trilinos.download]]
    sha256 = "56b05a138b6f99508b978138005406b685cedca9e76d067dd29e77576bffba9c"
    url = "https://github.com/JuliaBinaryWrappers/Trilinos_jll.jl/releases/download/Trilinos-v14.4.0+0/Trilinos.v14.4.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Trilinos]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c9fb049b99fa7c21f17960d738334d25fe40c3e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Trilinos.download]]
    sha256 = "e3f87793937863909a1ec8b072613c5d26c903698d23009114216f6e01ab21e3"
    url = "https://github.com/JuliaBinaryWrappers/Trilinos_jll.jl/releases/download/Trilinos-v14.4.0+0/Trilinos.v14.4.0.x86_64-linux-gnu-libgfortran5-cxx03.tar.gz"
[[Trilinos]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "00e5824ed0a638c5a8cc88a9ff65673002202828"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Trilinos.download]]
    sha256 = "21d776463b74154b2f47db3bcaf6118e92bbe81814348276cbf58a2f6f5a58f1"
    url = "https://github.com/JuliaBinaryWrappers/Trilinos_jll.jl/releases/download/Trilinos-v14.4.0+0/Trilinos.v14.4.0.x86_64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[Trilinos]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5a69f67ffae1a48129783844d09c341684a0a31"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Trilinos.download]]
    sha256 = "dd725eab3549e0954db4324ab7aa71242a47219c6b5b4b6d351b49e68427cbb3"
    url = "https://github.com/JuliaBinaryWrappers/Trilinos_jll.jl/releases/download/Trilinos-v14.4.0+0/Trilinos.v14.4.0.x86_64-linux-musl-libgfortran5-cxx03.tar.gz"
[[Trilinos]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9fcde93f5560783e633cc5f93ea57c62e2dc9a2"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Trilinos.download]]
    sha256 = "b764dc437c0b12093bb90de19231b683ca42f62b2d2fd8a5ff9c906005d4583c"
    url = "https://github.com/JuliaBinaryWrappers/Trilinos_jll.jl/releases/download/Trilinos-v14.4.0+0/Trilinos.v14.4.0.x86_64-linux-musl-libgfortran5-cxx11.tar.gz"
[[Trilinos]]
arch = "x86_64"
git-tree-sha1 = "74758ff1536d9fa2636e5d94b5f40443cd08a7ba"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Trilinos.download]]
    sha256 = "9b4ff8aa9c77c1268b33c24a53f9e1c6aeb2522aee7690d0b6388937e7a02af3"
    url = "https://github.com/JuliaBinaryWrappers/Trilinos_jll.jl/releases/download/Trilinos-v14.4.0+0/Trilinos.v14.4.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Trilinos]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d34b738d1e7939919e2099c2d25ddfed16c4824"
libgfortran_version = "5.0.0"
os = "windows"

    [[Trilinos.download]]
    sha256 = "c42f0558d438162cea6b8d43452a84a22d32f75e778cacface3d2e8a91a86121"
    url = "https://github.com/JuliaBinaryWrappers/Trilinos_jll.jl/releases/download/Trilinos-v14.4.0+0/Trilinos.v14.4.0.x86_64-w64-mingw32-libgfortran5-cxx03.tar.gz"
[[Trilinos]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a148961b44ea3c72b3800f76666a21cb0cdb540"
libgfortran_version = "5.0.0"
os = "windows"

    [[Trilinos.download]]
    sha256 = "057269240617f544beb525041fe313f82a2af3244c343955f32d0e15c2806c69"
    url = "https://github.com/JuliaBinaryWrappers/Trilinos_jll.jl/releases/download/Trilinos-v14.4.0+0/Trilinos.v14.4.0.x86_64-w64-mingw32-libgfortran5-cxx11.tar.gz"
