# Autogenerated wrapper script for Trilinos_jll for x86_64-w64-mingw32-libgfortran3-cxx03
export libamesos, libaztecoo, libbelos, libbelosepetra, libepetra, libepetraext, libifpack, libisorropia, libloca, liblocaepetra, liblocalapack, libnox, libnoxepetra, libnoxlapack, libsacado, libsimpi, libteuchoscomm, libteuchoscore, libteuchosnumerics, libteuchosparameterlist, libteuchosremainder, libtrilinoscouplings, libtrilinosss, libtriutils, libzoltan

using SuiteSparse_jll
using OpenBLAS32_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("Trilinos")
JLLWrappers.@declare_library_product(libamesos, "libamesos.dll")
JLLWrappers.@declare_library_product(libaztecoo, "libaztecoo.dll")
JLLWrappers.@declare_library_product(libbelos, "libbelos.dll")
JLLWrappers.@declare_library_product(libbelosepetra, "libbelosepetra.dll")
JLLWrappers.@declare_library_product(libepetra, "libepetra.dll")
JLLWrappers.@declare_library_product(libepetraext, "libepetraext.dll")
JLLWrappers.@declare_library_product(libifpack, "libifpack.dll")
JLLWrappers.@declare_library_product(libisorropia, "libisorropia.dll")
JLLWrappers.@declare_library_product(libloca, "libloca.dll")
JLLWrappers.@declare_library_product(liblocaepetra, "liblocaepetra.dll")
JLLWrappers.@declare_library_product(liblocalapack, "liblocalapack.dll")
JLLWrappers.@declare_library_product(libnox, "libnox.dll")
JLLWrappers.@declare_library_product(libnoxepetra, "libnoxepetra.dll")
JLLWrappers.@declare_library_product(libnoxlapack, "libnoxlapack.dll")
JLLWrappers.@declare_library_product(libsacado, "libsacado.dll")
JLLWrappers.@declare_library_product(libsimpi, "libsimpi.dll")
JLLWrappers.@declare_library_product(libteuchoscomm, "libteuchoscomm.dll")
JLLWrappers.@declare_library_product(libteuchoscore, "libteuchoscore.dll")
JLLWrappers.@declare_library_product(libteuchosnumerics, "libteuchosnumerics.dll")
JLLWrappers.@declare_library_product(libteuchosparameterlist, "libteuchosparameterlist.dll")
JLLWrappers.@declare_library_product(libteuchosremainder, "libteuchosremainder.dll")
JLLWrappers.@declare_library_product(libtrilinoscouplings, "libtrilinoscouplings.dll")
JLLWrappers.@declare_library_product(libtrilinosss, "libtrilinosss.dll")
JLLWrappers.@declare_library_product(libtriutils, "libtriutils.dll")
JLLWrappers.@declare_library_product(libzoltan, "libzoltan.dll")
function __init__()
    JLLWrappers.@generate_init_header(SuiteSparse_jll, OpenBLAS32_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libamesos,
        "bin\\libamesos.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libaztecoo,
        "bin\\libaztecoo.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libbelos,
        "bin\\libbelos.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libbelosepetra,
        "bin\\libbelosepetra.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libepetra,
        "bin\\libepetra.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libepetraext,
        "bin\\libepetraext.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libifpack,
        "bin\\libifpack.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libisorropia,
        "bin\\libisorropia.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libloca,
        "bin\\libloca.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblocaepetra,
        "bin\\liblocaepetra.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblocalapack,
        "bin\\liblocalapack.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnox,
        "bin\\libnox.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnoxepetra,
        "bin\\libnoxepetra.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnoxlapack,
        "bin\\libnoxlapack.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsacado,
        "bin\\libsacado.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsimpi,
        "bin\\libsimpi.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libteuchoscomm,
        "bin\\libteuchoscomm.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libteuchoscore,
        "bin\\libteuchoscore.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libteuchosnumerics,
        "bin\\libteuchosnumerics.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libteuchosparameterlist,
        "bin\\libteuchosparameterlist.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libteuchosremainder,
        "bin\\libteuchosremainder.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtrilinoscouplings,
        "bin\\libtrilinoscouplings.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtrilinosss,
        "bin\\libtrilinosss.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtriutils,
        "bin\\libtriutils.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libzoltan,
        "bin\\libzoltan.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
