# Autogenerated wrapper script for Trilinos_jll for x86_64-linux-gnu-libgfortran5-cxx11
export libamesos, libaztecoo, libbelos, libbelosepetra, libepetra, libepetraext, libifpack, libisorropia, libloca, liblocaepetra, liblocalapack, libnox, libnoxepetra, libnoxlapack, libsacado, libsimpi, libteuchoscomm, libteuchoscore, libteuchosnumerics, libteuchosparameterlist, libteuchosremainder, libtrilinoscouplings, libtrilinosss, libtriutils, libzoltan

using OpenBLAS32_jll
using SuiteSparse32_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("Trilinos")
JLLWrappers.@declare_library_product(libamesos, "libamesos.so.12")
JLLWrappers.@declare_library_product(libaztecoo, "libaztecoo.so.12")
JLLWrappers.@declare_library_product(libbelos, "libbelos.so.12")
JLLWrappers.@declare_library_product(libbelosepetra, "libbelosepetra.so.12")
JLLWrappers.@declare_library_product(libepetra, "libepetra.so.12")
JLLWrappers.@declare_library_product(libepetraext, "libepetraext.so.12")
JLLWrappers.@declare_library_product(libifpack, "libifpack.so.12")
JLLWrappers.@declare_library_product(libisorropia, "libisorropia.so.12")
JLLWrappers.@declare_library_product(libloca, "libloca.so.12")
JLLWrappers.@declare_library_product(liblocaepetra, "liblocaepetra.so.12")
JLLWrappers.@declare_library_product(liblocalapack, "liblocalapack.so.12")
JLLWrappers.@declare_library_product(libnox, "libnox.so.12")
JLLWrappers.@declare_library_product(libnoxepetra, "libnoxepetra.so.12")
JLLWrappers.@declare_library_product(libnoxlapack, "libnoxlapack.so.12")
JLLWrappers.@declare_library_product(libsacado, "libsacado.so.12")
JLLWrappers.@declare_library_product(libsimpi, "libsimpi.so.12")
JLLWrappers.@declare_library_product(libteuchoscomm, "libteuchoscomm.so.12")
JLLWrappers.@declare_library_product(libteuchoscore, "libteuchoscore.so.12")
JLLWrappers.@declare_library_product(libteuchosnumerics, "libteuchosnumerics.so.12")
JLLWrappers.@declare_library_product(libteuchosparameterlist, "libteuchosparameterlist.so.12")
JLLWrappers.@declare_library_product(libteuchosremainder, "libteuchosremainder.so.12")
JLLWrappers.@declare_library_product(libtrilinoscouplings, "libtrilinoscouplings.so.12")
JLLWrappers.@declare_library_product(libtrilinosss, "libtrilinosss.so.12")
JLLWrappers.@declare_library_product(libtriutils, "libtriutils.so.12")
JLLWrappers.@declare_library_product(libzoltan, "libzoltan.so.12")
function __init__()
    JLLWrappers.@generate_init_header(OpenBLAS32_jll, SuiteSparse32_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libamesos,
        "lib/libamesos.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libaztecoo,
        "lib/libaztecoo.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libbelos,
        "lib/libbelos.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libbelosepetra,
        "lib/libbelosepetra.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libepetra,
        "lib/libepetra.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libepetraext,
        "lib/libepetraext.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libifpack,
        "lib/libifpack.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libisorropia,
        "lib/libisorropia.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libloca,
        "lib/libloca.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblocaepetra,
        "lib/liblocaepetra.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblocalapack,
        "lib/liblocalapack.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnox,
        "lib/libnox.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnoxepetra,
        "lib/libnoxepetra.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnoxlapack,
        "lib/libnoxlapack.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsacado,
        "lib/libsacado.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsimpi,
        "lib/libsimpi.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libteuchoscomm,
        "lib/libteuchoscomm.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libteuchoscore,
        "lib/libteuchoscore.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libteuchosnumerics,
        "lib/libteuchosnumerics.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libteuchosparameterlist,
        "lib/libteuchosparameterlist.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libteuchosremainder,
        "lib/libteuchosremainder.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtrilinoscouplings,
        "lib/libtrilinoscouplings.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtrilinosss,
        "lib/libtrilinosss.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtriutils,
        "lib/libtriutils.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libzoltan,
        "lib/libzoltan.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
